name: issues output

on:
  issues:
    types:
      - opened


jobs:
  issues:
    runs-on: ubuntu-latest
    steps:
      - name: github context
        run: |
          echo "${{toJson(github.repository_owner)}}"
          echo "issue number:- ${{toJson(github.event.issue.number)}}"
          echo "issue url:- ${{toJson(github.event.issue.url)}}"


